### ISSUE TITLE
LaTeX/markdown formatting

### ISSUE THREAD

**Issue by JohnMcIntyreJR** [jr-packages/jrNotes#10]
There's a problem with the current LaTeX formatting checks. If I were to add a side note or margin note and include markdown formatting within it, no error appears when running "make final" or "make gitlab-check". This means that a load of asterisks and back ticks will pop up in the notes.

**Comment by trianglegirl** [comment]
@csgillespie Can there be a check added which:
Scans both \marginnotes & \sidenotes for any markdown formatting
Shows a warning message if any are found and highlights the location

**Comment by csgillespie** [comment]
@trianglegirl  What about:

- error for backticks 
- warnings for _ and *

Or should I just have warnings all around?

**Comment by JohnMcIntyreJR** [comment]
That sounds good. As long as errors don't manage to get past the gitlab check

**Comment by csgillespie** [comment]
This commit:
-  raises an error on backticks
- gives an info message on *
- Ignores `_` as these would raise latex errors anyway.

**Comment by trianglegirl** [comment]
Had a thought last night. Backticks are used legitimately in LaTeX as quotes `example' so you might need to downgrade the error to a warning.

**Comment by csgillespie** [comment]
Removed error
