### ISSUE TITLE
Add check_pkgtitle for python packages

### ISSUE THREAD

**Issue by csgillespie** [jr-packages/jrNotes#25]
We check that the package title matches for R packages.

**Comment by jwalton3141** [comment]
Should be closed by PR: #30

**Comment by jwalton3141** [comment]
NB.

Python packages **do not** have a `Title` entry (as R packages do).

 Instead, we may use their `summary` or `description` entry to record the desired "Jumping Rivers: {}".

 In PR #30 I opted to use `summary` to record the "package title".

As such we should consider the naming of `check_pkgtitle`, as we're not strictly checking a package "title" for python.

**Comment by jwalton3141** [comment]
Closed by #30 merge
