### ISSUE TITLE
Parallel doesn't seem to work well with Python

### ISSUE THREAD

**Issue by sebble** [jr-packages/jrNotes#3]
Segfault with Python notes and `cores >1`.  Only common factor seems to be Python and cores.  Further testing required?

https://github.com/jr-packages/jrNotes/blob/0c84221642d880899b6f125d13b44044fe8d4dfc/R/create_notes.R#L61

**Comment by csgillespie** [comment]
It works on my machine and it most work on others, e.g. Jamie, Jack, Rhian.

Is this a Windows and/or Mac issue?

**Comment by sebble** [comment]
Perhaps.

Verified: Problem exists on multiple Python notes repos, not on R notes repos (on Mac).

Pending: Matteo to verify with John

Pending: Seb to verify with Windows (other issues prohibited full testing)

**Comment by csgillespie** [comment]
Stale issue. As no-one has a Mac, closing for now.
