### ISSUE TITLE
Spelling mistakes are not ordered by chapter number

### ISSUE THREAD

**Issue by jwalton3141** [jr-packages/jrNotes#36]
`check_spelling.R` prints spelling mistakes to stdout, ordered alphabetically by mistake.

Sample output from `check_spelling.R`:

>     ℹ iloc  chapter4.Rmd:122
>     ℹ ing  chapter2.Rmd:207
>     ℹ interpeter  chapter2.Rmd:25
>     ℹ Jupyter  chapter1.Rmd:19,24,31
>     ℹ len  chapter3.Rmd:128

Note the order of chapters (4 , 2, 2, 1, 3) in the above.

I think that it'd be more useful if the sorting was grouped by chapter number:

>     ℹ Jupyter  chapter1.Rmd:19,24,31
>     ℹ ing  chapter2.Rmd:207
>     ℹ interpeter  chapter2.Rmd:25
>     ℹ len  chapter3.Rmd:128
>     ℹ iloc  chapter4.Rmd:122

**Comment by csgillespie** [comment]
@jwalton3141 I'm thinking that we should have a WORDLIST per course. It turns out (surprise!) that people ignore spelling mistakes.

**Comment by jwalton3141** [comment]
WORDLIST per course makes sense. At the _very_ least we should have a separate python WORDLIST and R WORDLIST.

**Comment by jwalton3141** [comment]
Opened #40 to keep a note of your comment.

_This_ issue was closed by #37
