### ISSUE TITLE
check_urls() doesn't print the domains of the problem urls

### ISSUE THREAD

**Issue by jwalton3141** [jr-packages/jrNotes#60]
- [ ]  If a URL does not have status 200 its status code is printed, but the URL generating the error isn't printed (see image below)
- [ ] URL's outputted from bash chunks have the `-` character protected as `{-}`, breaking the URL.

![image](https://user-images.githubusercontent.com/32269169/94574186-c0d67080-026a-11eb-86be-18a17f8aefb3.png)

**Comment by csgillespie** [comment]
Fixed by #62
